version: "3.8"                             ##version de docker compose

services:
  pgadmin:
   image: dpage/pgadmin4                    ##imagen de pgadmin
   environment:
     PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
     PGADMIN_DEFAULT_PASSWORD: "admin"
   ports:
    - "8000:8000"
   depends_on:
    - db