# Generated by Django 4.0.2 on 2022-02-14 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='autos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=20)),
                ('descrip', models.CharField(max_length=150)),
                ('precio', models.IntegerField()),
            ],
        ),
    ]
